version: "3.9"

networks:
  default:
    external:
      name: medication

services:
  app:
    container_name: storemanagement
    image: storemanagement
    ports:
      - 8085:8085
    networks:
      default:
        aliases:
          - storemanagement
    depends_on:
      - db

  db:
    image: mysql
    container_name: storemanagementdb
    ports:
      - 8088:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=storemanagement
    networks:
      default:
        aliases:
          - storemanagementdb

